# Generated by Django 4.2.1 on 2023-05-24 17:10

from django.db import migrations, models
import pdi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_title', models.CharField(max_length=25, verbose_name='Titulo do Objetivo')),
                ('developed_areas', models.CharField(max_length=100, verbose_name='Áreas ')),
                ('initial_datetime', models.DateTimeField(verbose_name='Data Inicio')),
                ('final_datetime', models.DateTimeField(verbose_name='Data Final')),
                ('reference_url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to=pdi.models.path_upload)),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
