# Generated by Django 4.2.1 on 2023-05-24 17:39

from django.db import migrations, models
import pdi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pdi.models.path_upload, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='reference_url',
            field=models.URLField(verbose_name='Link de Referência'),
        ),
    ]
